### ISSUE TITLE
Container -> Pod

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubernetes-network-policy-recipes#100]
The following image in the readme: 

![image](https://user-images.githubusercontent.com/159209/208788281-cc6ab4bc-e71c-493a-bf5e-b8d6f0793f5a.png)

I feel like we should change the wording to say Pod here (as containers might mean sidecars). I think back in the day I used this as a simplification but now that I look at it, it's maybe a gross simplification and does disservice.

The fix can be as easy as changing the Google Slides deck where they're sourced in, exporting gifs and feeding them to a gifmaker website.

**Comment by boredabdel** [comment]
Happy to do it. Where are the slides ?

**Comment by ahmetb** [comment]
I think I emailed them to you at some point. I no longer have access :/ searching in gdrive corp may help

**Comment by boredabdel** [comment]
I found them. Should have done an email search before i commented. I'm on it will send a PR your way next week
