### ISSUE TITLE
Are there examples using egress?

### ISSUE THREAD

**Issue by arobbins-akamai** [ahmetb/kubernetes-network-policy-recipes#103]
It seems that most or all of the examples here (which are great!) are based mainly on ingress rules. Can you provide some examples showing how to use egress rules?  In particular such that pods can be limited to connecting to certain other pods or external IPs, but also continue to have access to any necessary k8s services, such as DNS.  Thanks!

**Comment by boredabdel** [comment]
There are actually 3 egress examples:

Deny traffic from a namespace: https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/12-deny-all-non-whitelisted-traffic-from-the-namespace.md

Deny traffic from a namespace except DNS: https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/14-deny-external-egress-traffic.md

Deny traffic  from an app: https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/11-deny-egress-traffic-from-an-application.md

**Comment by arobbins-akamai** [comment]
Thanks for the pointers!
