### ISSUE TITLE
It's now possible to include a pod and namespace selector in policy.

### ISSUE THREAD

**Issue by mauilion** [ahmetb/kubernetes-network-policy-recipes#21]
https://github.com/kubernetes/kubernetes/pull/60452/commits/329639e9f6d330a7d8bdf4a0e76f55399cecfc2d has merged in 1.11 and now it can be used to allow pods from a specific namespace.

**Comment by ahmetb** [comment]
@mauilion thanks for notifying. Indeed we need an update...

It looks like this change was breaking, right? I assumed it was going to be implemented like `podAndNamespaceSelector:` but it looks like now the podSelector and namespaceSelector behavior can be combined.
