### ISSUE TITLE
Can't include podSelector into namespaceSelector

### ISSUE THREAD

**Issue by mont-x07** [ahmetb/kubernetes-network-policy-recipes#30]
Regarding this doc: https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/07-allow-traffic-from-some-pods-in-another-namespace.md
There is manifest which contain following lines:
```
ingress:
    - from:
      - namespaceSelector:     # chooses all pods in namespaces labelled with team=operations
          matchLabels:
            team: operations  
        podSelector:           # chooses pods with type=monitoring
          matchLabels:
            type: monitoring
```
I have tried to apply the same policy and got error:
```
The NetworkPolicy "test-policy" is invalid: spec.ingress[0].from[0]: Forbidden: may not specify more than 1 from type
```
Is it really possible to restricts traffic to pods with some label which placed in labelled namespaces?
If yes, please fix your manifest. Thanks!

P.S. Kubernetes cluster v.1.9.3 with Calico v.2.6

**Comment by ahmetb** [comment]
The doc you linked literally says "as of Kubernetes v1.11". :)
