### ISSUE TITLE
Add example of named ports 

### ISSUE THREAD

**Issue by noqcks** [ahmetb/kubernetes-network-policy-recipes#33]
09 describes that it is better to use named ports, but doesn't show how to use named ports. I think it would be useful to show how to implement a policy based on named ports!

> NOTE: Network Policies will not know the port numbers you exposed the application, such as 8001 and 5001. This is because they control inter-pod traffic and when you expose Pod as Service, ports are remapped like above. Therefore, you need to use the container port numbers (such as 8000 and 5000) in the NetworkPolicy specification. An alternative less error prone is to refer to the port names (such as metrics and http).

Thanks you for this great resources @ahmetb 🙏

**Comment by ahmetb** [comment]
That's a good point but I kinda expect people to search "kubernetes port names" (beware: nowadays kubernetes.io documentation fell off of Google index due to some mistake) and figure it out.
