### ISSUE TITLE
Error shows when apply "allow-traffic-from-some-pods-in-another-namespace"

### ISSUE THREAD

**Issue by nghyjohn** [ahmetb/kubernetes-network-policy-recipes#35]
when apply this policy,
error shows:

The NetworkPolicy "web-allow-all-ns-monitoring" is invalid: spec.ingress[0].from[0]: Forbidden: may not specify more than 1 from type

**Comment by nghyjohn** [comment]
Does this policy requires k8s v1.11 and calico v3.1.3 ?

**Comment by jwalker343** [comment]
I just ran into this as well. This example requires kubernetes v1.11 for API spec to even allow the policy to be created, I assume that calico also has to be updated to support that policy as well.

**Comment by ahmetb** [comment]
Yeah it’s noted that this policy requires Kubernetes 1.11 minimum. 

We don’t document which version of which network plugin supports this feature (there are a lot of plugins). It’s always a good idea to test your policies manually.
