### ISSUE TITLE
Example recipe for isolating service namespaces ?

### ISSUE THREAD

**Issue by srampal** [ahmetb/kubernetes-network-policy-recipes#37]
I dont see this here but is anyone aware of a network policy recipe/ design guide for isolating certain "control plane" namespaces from application namespaces while allowing for certain namespaces to use day-n monitoring services (such as Prometheus, EFK) to also run in a "day n services" namespace and service all application namespaces ? I realize this is a slightly open ended question perhaps but looking for any white papers/ recipes/ recommended segmentation topologies that someone may have already prepared for the purpose of control plane-data plane protection and isolation with the aim of a "secure by default" kubernetes cluster model.

**Comment by ahmetb** [comment]
I agree this is more of a recommendation topic and not so much of a recipe.

I recently gave a talk about [Kubernetes multi-tenancy](https://ahmet.im/blog/google-cloud-next-18/) and here's what I recommended:

1. when you create a namespace "foo", apply the `deny-all-ingress` to all pods in "foo"
2. then, only whitelist the stuff that needs access to pods in "foo"
3. make sure you can automate (1) –for that we have "GKE Policy Management" feature.

**Comment by srampal** [comment]
Agreed.  There are some more details of course … for instance in the example recommendations you listed below, we would also need RBAC policies that prevent namespaxce users fro mchanging their network policies to over-ride this isolation … however at the same time we still need to allow them to create other network policies for isolating/ or non-isolating between different tiers of their application within a single namespace. So we need some types of network policies that are only configurable by the cluster admin or namespace admin and some that are also configurable by application developers/ normal users.  Hence I was looking to see if someone has already done such an analysis and provided any suggested recommendations … if not, I would be happy to briefly discuss/ work with you or anyone interested in collaborating on this (and similarly there also issues with need for selective rbac and selective filtering when using day-N monitoring services running in special service namespaces).

**Comment by ahmetb** [comment]
@srampal Yeah this is a multitenancy discussion alright :) I'll close this issue.

I recommend you to:

1. watch [davidopp's multi-tenancy talk](https://www.youtube.com/watch?v=xygE8DbwJ7c) from kubecon eu
  a. watch my talk I linked above (they're very similar)
2. participate in `wg-kubernetes-multitenancy` [email list](https://groups.google.com/forum/#!forum/kubernetes-wg-multitenancy) which is under Kubernetes Community efforts.

This repo isn't the right forum to ask/discuss this. Your question is way beyond network policies.
