### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by magick93** [ahmetb/kubernetes-network-policy-recipes#38]
Hello

This issue is a request for advice.

I'm interested to hear any recommendations for network policy testing.

Specifically, I'm looking for something I can integrate into a pipeline.

**Comment by ahmetb** [comment]
Not the right place to ask this. Please ask on Kubernetes community forums etc.

**Comment by magick93** [comment]
I dont think the Kubernetes community will know how you have tested your recipes.

How have you tested these recipes?

**Comment by ahmetb** [comment]
This is unrelated.

You’re asking how you can test/validate recipes from CI/CD. I cannot recommend you anything. 

I tested the recipes to the extent that I found and reported bugs on various network plugins.

**Comment by magick93** [comment]
Ok. I've updated my original question to remove references to ci. 

> I tested the recipes to the extent that I found and reported bugs on various network plugins.

This is specifically what I am interested in. How did you test these recipes? 

Thanks

**Comment by ahmetb** [comment]
I've done manual testing in a test matrix with targets like pods within namespace, outside namespace, from/to load balancers, from/to CIDRs, from/to public internet.

**Comment by ahmetb** [comment]
That said I was trying to test the network policy plugins themselves.

Testing network policies in general is a more philosophical question probably should be discussed elsewhere.
