### ISSUE TITLE
Example request: NetworkPolicyPeer

### ISSUE THREAD

**Issue by naseemkullah** [ahmetb/kubernetes-network-policy-recipes#41]
Hi @ahmetb,
Could you kindly add one or more examples where netpol allows ingress from a specific group of pods from a different namespace please!

**Comment by ahmetb** [comment]
https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/07-allow-traffic-from-some-pods-in-another-namespace.md

**Comment by naseemkullah** [comment]
My apologies, for some reason I presumed it would be the last or one of the last examples.

Awesome thanks!
