### ISSUE TITLE
Deny access from other namespaces does not work when using svc fqdn

### ISSUE THREAD

**Issue by letavia** [ahmetb/kubernetes-network-policy-recipes#42]
I have a database in namespace1 which I deployed using statefulset and accessed through a service. 
An application from namespace2 manages to access this database using the database service FQDN. I want to shut the access from the app to this database using network policy, but it didn't work. 
 
I have tried several scenarios:
- Deny access from all other namespaces
- Deny access specifically from namespace2 using labels
- Allow access only from namespace1 using labels

Am I missing something here? Would it be better to apply deny-all policy first and then open up policy for each pod/namespace?

**Comment by ahmetb** [comment]
No. If https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/04-deny-traffic-from-other-namespaces.md isn’t working for you, you may not have a networkpolicy plugin installed, or it’s buggy.

**Comment by letavia** [comment]
Sorry I forgot to mention, I have my cluster on GKE with Calico net plugin installed (by enabling it in the cluster configuration)

**Comment by ahmetb** [comment]
> Deny access specifically from namespace2 using labels

How did you try this? Network Policies only allow things. There’s no deny rule. Paste a few yamls you tried.

Also you should ask this on stackoverflow ideally.
