### ISSUE TITLE
Allow trafic from kubelet

### ISSUE THREAD

**Issue by josericardomcastro** [ahmetb/kubernetes-network-policy-recipes#44]
Hi!

I deny all traffic to my pod, but now my probes (liveness and deadiness) are not working anymore.

How can i allow traffic only from kubelet?

**Comment by ahmetb** [comment]
kubelet should not be subject to network policies.

If you're seeing otherwise, please open a bug to your Network Policy plugin or Kubernetes project.

Also, this is not a support forum for kubernetes or network policies.
