### ISSUE TITLE
Document egress rules

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubernetes-network-policy-recipes#5]
Once they become available on GKE.

**Comment by puja108** [comment]
This would be awesome as there's no documentation around egress. Is it still not available on GKE?

**Comment by ahmetb** [comment]
@puja108 I don’t think it's available on GKE yet.

**Comment by puja108** [comment]
I see. If you need a test cluster with egress support, glad to give you a test cluster on one of our AWS control planes (sadly none on GCP, yet, but hopefully sometime next year).

**Comment by ahmetb** [comment]
I started writing some egress rules since `1.8.4-gke.0` now supports egress policies:

https://github.com/ahmetb/kubernetes-networkpolicy-tutorial/blob/master/11-deny-egress-traffic-from-an-application.md
https://github.com/ahmetb/kubernetes-networkpolicy-tutorial/blob/master/14-deny-external-egress-traffic.md

Hopefully I'll contribute more after my KubeCon talk on the subject.
