### ISSUE TITLE
Requirement for accessing external public URL's from pods

### ISSUE THREAD

**Issue by saiharshitachava** [ahmetb/kubernetes-network-policy-recipes#55]
We  have a huge cluster and whenever we want the deployment to communicate to the public URL's..We will have to open up proxy for all the nodes in the cluster (as we are behind a proxy)

Whenever we add a new node we need to make sure all of the rules are working as the kubernetes pods can spin anywhere in the cluster..

Can this requirement be achieved using any of the network policies in this project?(Im pretty new to this concept and I guess there can be some egress rules written)

**Comment by ahmetb** [comment]
Stackoverflow is a better forum for questions like these.
