### ISSUE TITLE
Add a case for allowing traffic from namespace without labels , like using namespaceselector with matchExpressions or some other option

### ISSUE THREAD

**Issue by learning813** [ahmetb/kubernetes-network-policy-recipes#76]
There are chances for challenges where there is no labels given to pod to a namespace but we need to allow all pods from that namespace 

Can we please add an example for a namespace selector where a namespace is selected based on the namespace's name rather than the labels on its pod ( a common CKA question), I tried namespace selector with matchExpressions but that did not work in exam

**Comment by boredabdel** [comment]
Will this be a good example 

https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/05-allow-traffic-from-all-namespaces.md ?
