### ISSUE TITLE
What about a selector for a PV when it needs to access NFS Pod

### ISSUE THREAD

**Issue by luisvillarreal** [ahmetb/kubernetes-network-policy-recipes#79]
I used,
[DENY all traffic from other namespaces](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/04-deny-traffic-from-other-namespaces.md)

But looks like the PV is considered a different-namespace resource. Then, 

[ALLOW traffic from some pods in another namespace](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/07-allow-traffic-from-some-pods-in-another-namespace.md)

to treat the PV as an outter-ns Pod and labeled it but didn't work either.

```
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/a21b800b-0bce-41bd-b8f2-cbb4bfbd83f1/volumes/kubernetes.io~nfs/my-pv-f9da82d12a6f00abb20b832e9dadc879 --scope -- /home/kubernetes/containerized_mounter/mounter mount -t nfs nfs-server-svc.mynamespace.svc.cluster.local:/ /var/lib/kubelet/pods/a21b800b-0bce-41bd-b8f2-cbb4bfbd83f1/volumes/kubernetes.io~nfs/my-pv-f9da82d12a6f00abb20b832e9dadc879
Output: Running scope as unit: run-rdc06e260917a44f19efba49ee227e0ef.scope
Mount failed: mount failed: exit status 32
Mounting command: chroot
Mounting arguments: [/home/kubernetes/containerized_mounter/rootfs mount -t nfs nfs-server-svc.mynamespace.svc.cluster.local:/ /var/lib/kubelet/pods/a21b800b-0bce-41bd-b8f2-cbb4bfbd83f1/volumes/kubernetes.io~nfs/my-pv-f9da82d12a6f00abb20b832e9dadc879]
```

**Comment by ahmetb** [comment]
I am not sure how network policies are relevant in the context of persistent volume APIs. Is this a thing? Please link to the relevant documentation.

**Comment by luisvillarreal** [comment]
No worries, I checked with Google and looks like the plain vanilla NP will not address this. Thank you
