### ISSUE TITLE
--generator=run-pod/v1 is deprecated & removed in the latest versions - It should be removed

### ISSUE THREAD

**Issue by avinashdesireddy** [ahmetb/kubernetes-network-policy-recipes#85]
`--generator=run-pod/v1` is deprecated & removed in the latest versions - It should be removed.

Commands, where `generator=run-pod/v1` is used, should be updated.

From
```
kubectl run --generator=run-pod/v1 test-$RANDOM --namespace=default --rm -i -t --image=alpine -- sh 
```
to 
```
kubectl run test-$RANDOM --namespace=default --rm -i -t --image=alpine -- sh 
```

**Comment by avinashdesireddy** [comment]
I started working on the changes, will submit PR soon

**Comment by boredabdel** [comment]
Thanks for raising this, when you are ready with a PR send it my way and i'd be happy to review it.
